export const ITEMS_REQUEST = 'ITEMS_REQUEST';
export const ITEMS_SUCCESS = 'ITEMS_SUCCESS';
export const ITEMS_FAILURE = 'ITEMS_FAILURE';
export const ITEMS_CLEAN = 'ITEMS_CLEAN';
export const ITEM_SELECTED = 'ITEM_SELECTED';